version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    environment:
      # Laravel config
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      APP_URL: http://localhost:8005
      VITE_APP_URL: http://localhost:8005